export const products = [
  {
    id: 1,
    title: "Whatever People Say I Am, That's What I'm Not",
    image:
      'https://upload.wikimedia.org/wikipedia/en/5/5f/Whatever_People_Say_I_Am%2C_That%27s_What_I%27m_Not.jpg',
    artist: 'Arctic Monkeys',
    price: 19.99,
    year: 2006,
    label: 'Domino',
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'The View From the Afternoon',
      'I Bet That You Look Good on the Dancefloor',
      'Fake Tales of San Francisco',
      'Dancing Shoes',
      "You Probably Coudn't See for the Lights but You Were Staring Straight at Me",
      'Still Take You Home',
      'Riot Van',
      'Red Light Indicates Doors Are Secured',
      'Mardy Bum',
      'Perhaps Vampies Is a Bit Strong But...',
      'When the Sun Goes Down',
      'From the Ritz to the Rubble',
      'A Certain Romance',
    ],
    description: `Alright kid, you stick to your father like glue and make sure that he takes her to the dance. Okay, alright, I'll prove it to you. Look at my driver's license, expires 1987. Look at my birthday, for crying out load I haven't even been born yet. And, look at this picture, my brother, my sister, and me. Look at the sweatshirt, Doc, class of 1984. Hey Biff, check out this guy's life preserver, dork thinks he's gonna drown. Are those my clocks I hear? Yeah, who are you?

    Good morning, Mom. Oh, Marty, I almost forgot, Jennifer Parker called. Thank god I still got my hair. What on Earth is that thing I'm wearing? That's George McFly. Look, there's a rhythmic ceremonial ritual coming up. Shape up, man. You're a slacker. You wanna be a slacker for the rest of your life?
    `,
  },
  {
    id: 2,
    title: 'Favourite Worst Nightmare',
    image:
      'https://upload.wikimedia.org/wikipedia/en/a/ae/Favourite_Worst_Nightmare.jpg',
    artist: 'Arctic Monkeys',
    price: 19.99,
    year: 2007,
    label: 'Domino',
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'Brianstorm',
      'Teddy Picker',
      'D is for Dangerous',
      'Balaclava',
      'Fluorescent Adolescent',
      'Only Ones Who Know',
      'Do Me a Favour',
      'This House Is a Circus',
      'If You Were There, Beware',
      'The Bad Thing',
      'Old Yellow Bricks',
      '505',
    ],
    description: `What, right here right now in the cafeteria? What if she said no? I don't know if I could take that kind of rejection. Besides, I think she'd rather go with somebody else. No no no this sucker's electrical, but I need a nuclear reaction to generate the one point twenty-one gigawatts of electricity that I need. I followed you. Doc, Doc. Oh, no. You're alive. Bullet proof vest, how did you know, I never got a chance to tell you. About all that talk about screwing up future events, the space time continuum. Right.

    About 30 years, it's a nice round number. Excuse me. About how far ahead are you going? That's George McFly? What?
    `,
  },
  {
    id: 3,
    title: 'Humbug',
    image:
      'https://upload.wikimedia.org/wikipedia/en/2/20/Arcticmonkeys-humbug.jpg',
    artist: 'Arctic Monkeys',
    price: 19.99,
    year: 2009,
    label: 'Domino',
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'My Propellor',
      'Crying Lightning',
      'Dangerous Animals',
      'Secret Door',
      'Potion Approching',
      'Fire and the Thud',
      'Cornerstone',
      'Dance Little Liar',
      'Pretty Visitors',
      "The Jeweller's Hands",
    ],
    description: `What, I don't get what happened. After I fell off my toilet, I drew this. Okay, real mature guys. Okay, Biff, will you pick up my books? What's that thing he's on? Well, Biff.

    Working. Believe me, Marty, you're better off not having to worry about all the aggravation and headaches of playing at that dance. What the hell is a gigawatt? Well looky what we have here. No no no, you're staying right here with me. Holy shit.
    `,
  },
  {
    id: 4,
    title: 'Suck It and See',
    image:
      'https://images-na.ssl-images-amazon.com/images/I/51QTqyFN%2B%2BL._AC_SL1417_.jpg',
    artist: 'Arctic Monkeys',
    price: 19.99,
    year: 2011,
    label: 'Domino',
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      "She's Thunderstorms",
      'Black Treacle',
      'Brick by Brick',
      'The Hellcat Spangled Shalalala',
      "Don't Sit Down 'Cause I've Moved Your Chair",
      'Library Pictures',
      'All My Own Stunts',
      'Reckless Serenade',
      'Piledriver Waltz',
      'Love Is a Laserquest',
      'Suck It and See',
      "That's Where You're Wrong",
    ],
    description: `Hey Biff, check out this guy's life preserver, dork thinks he's gonna drown. Alright, we're the pinheads. Well, Marty, I'm almost eighteen-years-old, it's not like I've never parked before. Hey, don't I know you from somewhere? Your not gonna be picking a fight, Dad, dad dad daddy-o. You're coming to a rescue, right? Okay, let's go over the plan again. 8:55, where are you gonna be.

    He's an absolute dream. A bolt of lightning, unfortunately, you never know when or where it's ever gonna strike. Hey wait, wait a minute, who are you? Stella, another one of these damn kids jumped in front of my car. Come on out here, help me take him in the house. Oh. Really.
    `,
  },
  {
    id: 5,
    title: 'AM',
    image:
      'https://images-na.ssl-images-amazon.com/images/I/71hEtk3aCpL._AC_SY355_.jpg',
    artist: 'Arctic Monkeys',
    price: 19.99,
    year: 2013,
    label: 'Domino',
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'Do I Wanna Know?',
      'R U Mine?',
      'One For the Road',
      'Arabella',
      'I Want It All',
      'No.1 Party Anthem',
      'Mad Sounds',
      'Fireside',
      "Why'd You Only Call Me When You're High?",
      'Snap Out of It',
      'Knee Socks',
      'I Wanna Be Yours',
    ],
    description: `Huh? That was so stupid, Grandpa hit him with the car. You bet. Last night, Darth Vader came down from planet Vulcan. And he told me that if I didn't take Lorraine, that he'd melt my brain. Ahh.

    Hey Biff, check out this guy's life preserver, dork thinks he's gonna drown. Wait a minute, what are you doing, Doc? Just say anything, George, say what ever's natural, the first thing that comes to your mind. Oh, great scott. You get the cable, I'll throw the rope down to you. What?
    `,
  },
  {
    id: 6,
    title: 'Royal Blood',
    image:
      'https://cdn.hmv.com/r/w-1280/hmv/files/8e/8ed1f219-9fdb-4463-a766-bd67c0923d6b.jpg',
    artist: 'Royal Blood',
    price: 19.99,
    year: 2014,
    label: 'Warner Bros.',
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'Out of the Black',
      'Come On Over',
      'Figure It Out',
      'You Can Be So Cruel',
      'Blood Hands',
      'Little Monster',
      'Loose Change',
      'Careless',
      'Ten Tonne Skeleton',
      'Better Strangers',
    ],
    description: `Yeah, I'll keep that in mind. Yeah, sure, okay. Thank you. In about thirty years. Whoa, whoa, okay. Oh, if Paul calls me tell him I'm working at the boutique late tonight.

    That's a great idea. I'd love to park. Jennifer. Good morning, Mom. No no no, Doc, I just got here, okay, Jennifer's here, we're gonna take the new truck for a spin. I'm, I'm sorry, Mr. McFly, I mean, I was just starting on the second coat.`,
  },
  {
    id: 7,
    title: 'Currents',
    artist: 'Tame Impala',
    image:
      'https://images-na.ssl-images-amazon.com/images/I/A1LVEJikmZL._AC_SL1500_.jpg',
    price: 24.99,
    year: 2015,
    label: 'Modular',
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'Let It Happen',
      'Nangs',
      'The Moment',
      "Yes I'm Changing",
      'Eventually',
      'Gossip',
      'The Less I Know the Better',
      'Past Life',
      'Disciples',
      "'Cause I'm a Man",
      'Reality in Motion',
      'Love/Paranoia',
      'New Person, Same Old Mistakes',
    ],
    description: `Just finishing up the second coat now. Y'know this time it wasn't my fault. The Doc set all of his clocks twenty-five minutes slow. Watch this. Not me, the car, the car. My calculations are correct, when this baby hits eighty-eight miles per hour, your gonna see some serious shit. Watch this, watch this. Ha, what did I tell you, eighty-eight miles per hour. The temporal displacement occurred at exactly 1:20 a.m. and zero seconds. Doc, you gotta help- Hey Dad, George, hey, you on the bike.

    George. Hey I'm talking to you, McFly, you Irish bug. Look, there's a rhythmic ceremonial ritual coming up. Okay, okay you guys, oh ha ha ha very funny. Hey you guys are being real mature. I guess you guys aren't ready for that yet. But your kids are gonna love it.`,
  },
  {
    id: 8,
    title: "Who's Next",
    artist: 'The Who',
    image:
      'https://www.thisdayinmusic.com/wp-content/uploads/2018/05/whos-next.jpg',
    price: 19.99,
    year: 1971,
    label: 'Track',
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      "Baba O'Riley",
      'Bargain',
      "Love Ain't for Keeping",
      'My Wife',
      'The Song Is Over',
      'Getting in Tune',
      'Going Mobile',
      'Behind Blue Eyes',
      "Won't Get Fooled Again",
    ],
    description: `Yeah, he's right here. Did you hurt your head? About how far ahead are you going? Ohh, no. Radiation suit, of course, cause all of the fall out from the atomic wars. This is truly amazing, a portable television studio. No wonder your president has to be an actor, he's gotta look good on television.

    Alright, let's set your destination time. This is the exact time you left. I'm gonna send you back at exactly the same time. It's be like you never left. Now, I painted a white line on the street way over there, that's where you start from. I've calculated the distance and wind resistance fresh to active from the moment the lightning strikes, at exactly 7 minutes and 22 seconds. When this alarm goes off you hit the gas. Hey, not too early I sleep in on Saturday. Oh, McFly, your shoe's untied. Don't be so gullible, McFly. You got the place fixed up nice, McFly. I have you're car towed all the way to your house and all you've got for me is light beer. What are you looking at, butthead. Say hi to your mom for me. Leave her alone, you bastard. It's already mutated into human form, shoot it. Marty, is that you?`,
  },
  {
    id: 9,
    title: 'Breakfast in America',
    image:
      'https://upload.wikimedia.org/wikipedia/en/c/c4/Supertramp_-_Breakfast_in_America.jpg',
    artist: 'Supertramp',
    price: 22.99,
    year: 1979,
    label: 'A&M',
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'Gone Hollywood',
      'The Logical Song',
      'Goodbye Stranger',
      'Breakfast in America',
      'Oh Darling',
      'Take the Long Way Home',
      'Lord Is It Mine',
      'Just Another Nervous Wreck',
      'Casual Conversations',
      'Child of Vision',
    ],
    description: `What? Back to the future. I over slept, look I need your help. I have to ask Lorraine out but I don't know how to do it. I have to ask Lorraine out but I don't know how to do it. Of course, the Enchantment Under The Sea Dance they're supposed to go to this, that's where they kiss for the first time. You do?

    Doc, she didn't even look at him. Doc, you don't just walk into a store and ask for plutonium. Did you rip this off? Ohh, no. The storm. No, Biff, you leave her alone.`,
  },
  {
    id: 10,
    title: 'Dark Side of the Moon',
    image:
      'https://images-na.ssl-images-amazon.com/images/I/51UtWpxbNYL._AC_SL1500_.jpg',
    artist: 'Pink Floyd',
    price: 19.99,
    year: 1973,
    label: 'Harvest',
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'Speak to Me',
      'Breathe',
      'On the Run',
      'Time',
      'The Great Gig in the Sky',
      'Money',
      'Us and Them',
      'Any Colour You Like',
      'Brain Damage',
      'Eclipse',
    ],
    description: `Oh, great scott. You get the cable, I'll throw the rope down to you. What you got under here? Doc. I haven't Look me up when you get there, guess I'll be about 47.

    Of course, from a group of Libyan Nationalists. They wanted me to build them a bomb, so I took their plutonium and in turn gave them a shiny bomb case full of used pinball machine parts. You extol me with a lot of confidence, Doc. That's a big bruise you have there. Marty, I'm sorry, but the only power source capable of generating one point twenty-one gigawatts of electricity is a bolt of lightning. Yeah Mom, we know, you've told us this story a million times. You felt sorry for him so you decided to go with him to The Fish Under The Sea Dance.`,
  },
  {
    id: 11,
    title: 'Led Zeppelin I',
    artist: 'Led Zeppelin',
    image:
      'https://images-na.ssl-images-amazon.com/images/I/51SUWsbmnHL._AC_.jpg',
    price: 14.99,
    year: 1969,
    label: 'Atlantic',
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'Good Times Bad Times',
      "Babe I'm Gonna Leave You",
      'You Shook Me',
      'Dazed and Confused',
      'Your Time Is Gonna Come',
      'Black Mountain Side',
      'Communication Breakdown',
      "I Can't Quit You Baby",
      'How Many More Times',
    ],
    description: `Let's put him in there. I over slept, look I need your help. I have to ask Lorraine out but I don't know how to do it. I have to ask Lorraine out but I don't know how to do it. Well, you mean, it makes perfect sense. Quiet, quiet. I'm gonna read your thoughts. Let's see now, you've come from a great distance? Yeah, well uh, lets keep this brain melting stuff to ourselves, okay?

    Hey, Doc, we better back up, we don't have enough roads to get up to 88. Alright, okay listen, keep your pants on, she's over in the cafe. God, how do you do this? What made you change your mind, George? Next, please. Hey George, heard you laid out Biff, nice going. Yeah, I'll keep that in mind.`,
  },
  {
    id: 12,
    title: 'Costello Music',
    artist: 'The Fratellis',
    image:
      'https://upload.wikimedia.org/wikipedia/en/c/c8/TheFratellis-CostelloMusic.jpg',
    price: 19.99,
    year: 2006,
    label: 'Fallout',
    inCart: false,
    count: 0,
    total: 0,
    tracklist: [
      'Henrietta',
      'Flathead',
      'Cuntry Boys & City Girls',
      'Whistle for the Choir',
      'Chelsea Dagger',
      'For the Girl',
      'Doginabag',
      'Creepin Up The Backstairs',
      'Vince the Loveable Stoner',
      'Everybody Knows You Cried Last Night',
      'Baby Fratelli',
      'Got Ma Nuts from a Hippy',
      'Ole Black ‘n’ Blue Eyes',
    ],
    description: `What? Good, I'll see you tonight. Don't forget, now, 1:15 a.m., Twin Pines Mall. Welcome to my latest experiment. It's the one I've been waiting for all my life. Oh, oh Marty, here's your keys. You're all waxed up, ready for tonight. Stop it.

    Perfect, just perfect. No no no this sucker's electrical, but I need a nuclear reaction to generate the one point twenty-one gigawatts of electricity that I need. Calm down, Marty, I didn't disintegrate anything. The molecular structure of Einstein and the car are completely intact. So tell me, Marty, how long have you been in port? Yet.`,
  },
];
